### ISSUE TITLE
Broken link to API / tutorials

### ISSUE THREAD

**Issue by mariemoullet** [NKI-CCB/sobolev_alignment#1]
### Report

Hello! Very interesting method, I was wondering if there was a plan to release the notebooks used to generate the figures in the manuscript? The link to the [API](https://sobolev-alignment.readthedocs.io/en/latest/api.html) also appears to be broken, would it be possible to update this? thank you so much for your help!

**Comment by saroudant** [comment]
Dear @mariemoullet,

Thanks a lot for your interest in the method. I am currently working on the final release. In the mean-time:
- You can already consult the documentation inside the package. An early version of the doc can be found here: https://sobolev-alignment.readthedocs.io/en/latest/ . I am still running into some issue with readthedocs, as I am new to it. I will be fixing it ASAP.

- The noteboks are available here: https://github.com/NKI-CCB/sobolev_alignment_manuscript
I will be uploading some final code next week, but the bulk of the results are there. Don't hesitate to let me know if you run into any issue.

Best regards,
Soufiane

**Comment by mariemoullet** [comment]
Hi Soufiane, I wasn't aware of the manuscript repo, this is very helpful thank you!
